### ISSUE TITLE
Fabric Renderer API should be updated

### ISSUE THREAD

**Issue by YSYavuzSelim** [QuiltMC/quilted-fabric-api#130] opened 2023-09-27 15:04 UTC
![image](https://github.com/QuiltMC/quilted-fabric-api/assets/79472692/02a93697-9848-4d0c-b3e4-93ecb4693081)
Fabric-Renderer-api in 1.19.4 is at version 2.3.1 but the mod that I am using (Indium) needs 2.4.0

**Comment by YSYavuzSelim** [comment] 2023-09-27 15:04
I am using the latest version of QFapi on 1.19.4

**Comment by Poopooracoocoo** [comment] 2023-09-27 19:29
> I am using the latest version of QFapi on 1.19.4

... Define latest.

**Comment by rinOfTheStars** [comment] 2023-09-27 23:35
This is a duplicate of https://github.com/QuiltMC/quilted-fabric-api/issues/123 and https://github.com/QuiltMC/quilted-fabric-api/issues/114

**Comment by rinOfTheStars** [comment] 2023-10-04 03:33
Can now be closed as of #132

**Closed as completed** 2023-10-04 03:34 UTC
