### ISSUE TITLE
Can't play on servers

### ISSUE THREAD

**Issue by ManInMyVan** [QuiltMC/quilted-fabric-api#52] opened 2022-12-09 02:34 UTC
With only the quilt loader & qfapi loaded (it works when I don't have qfapi), I get [this](https://imgur.com/a/Y57r8aF) when I join a server

**Comment by triphora** [comment] 2022-12-09 03:03
This is a duplicate of QuiltMC/quilt-standard-libraries#232 which has much more technical detail about the issue.

**Comment by LambdAurora** [comment] 2022-12-10 11:40
This has been fixed with [`eb0acc1`](https://github.com/QuiltMC/quilt-standard-libraries/commit/eb0acc171a058e7fc9de02bf0ea57a388013a530) and the latest Quilted Fabric API release.

**Closed as completed by LambdAurora** 2022-12-10 11:40 UTC
