### ISSUE TITLE
Support 1.20.6

### ISSUE THREAD

**Issue by GGORG0** [QuiltMC/quilted-fabric-api#159] opened 2024-04-24 16:31 UTC
It just came out yesterday and Fabric is, as always, immediately up to date

**Comment by OroArmor** [comment] 2024-04-24 16:58
I know. I'm not stupid. It's awesome that fabric has several developers to help it update while I'm maintaining more more than them over 3 versions. It'll come when it'll come. It won't take as long as 1.20.4, but I would expect at least two weeks minimum for qfapi.

There is also a possibility that quilt entirely skips qfapi for 1.20.5 as the code has gotten extremely difficult to maintain and has more issues than I can count.

**Comment by FirstMegaGame4** [comment] 2024-04-24 16:58
@OroArmor seems that the curse of people asking for the newest version is back again. Hope they won't be disrespectful...

So @GGORG0
> **Where's QSL/QFAPI for 1.20.5 MC version?** 
> The Quilt devs have physical world responsibilities and other stuff to deal with. Asking when will QSL/QFAPI 1.20.5 release will not make them release said Quilt thing any faster so please stop asking.

**Comment by GGORG0** [comment] 2024-04-24 17:02
Yeah, I do know that. I just wanted to make sure it won't take, *how long?*, almost a year

Btw what are the advantages of using qfapi over fabric API (for users not developers)?
From what I remember the regular fabric API works perfectly on quilt too...

**Comment by FirstMegaGame4** [comment] 2024-04-24 17:03
> Yeah, I do know that. I just wanted to make sure it won't take, _how long?_, almost a year
> 
> Btw what are the advantages of using qfapi over fabric API (for users not developers)? From what I remember the regular fabric API works perfectly on quilt too...

FAPI and QSL are incompatible. QFAPI is a compatibility layer between FAPI & QSL that works by reimplmenting FAPI stuff on top of QSL.

**Comment by NicoNekoDev** [comment] 2024-04-29 18:26
This should just go straight to 1.20.6 instead

**Comment by FirstMegaGame4** [comment] 2024-04-29 18:27
> This should just go straight to 1.20.6 instead

1.20.5 & 1.20.6 are very likely same version. It's the same situation it was between 1.20.3 & 1.20.4.
It means that it will probably still stays in a single version for the two ones.

**Comment by Soulfate24** [comment] 2024-05-07 15:09
> I know. I'm not stupid. It's awesome that fabric has several developers to help it update while I'm maintaining more more than them over 3 versions. It'll come when it'll come. It won't take as long as 1.20.4, but I would expect at least two weeks minimum for qfapi.

It feels like there's too much pressure on your shoulders. QUILT deserves as much attention as FABRIC already gets. I hope that the talents will soon be challenged by the amount of work to be done on this project, because if not, a call for help will have to be organised. I regret more and more that I wasn't interested in Java, I can only help with the multimedia side (audio, video, image).

**Comment by ghost** [comment] 2024-05-09 09:40
@Soulfate24 there is always time to learn new languages. The issue is how to prevent devs doing the same thing concurrently - you don't want to spend a ton of time merging commits when you could have spent that time fixing bugs.

**Comment by TheGlitch76** [comment] 2024-07-04 01:34
Released as QFAPI 10.0.0-alpha.2 ([Modrinth](https://modrinth.com/mod/qsl/version/10.0.0-alpha.2+0.100.4-1.20.6))

**Closed as completed by TheGlitch76** 2024-07-04 01:34 UTC
Labels: upstream sync

**Comment by ghost** [comment] 2024-07-04 07:22
WOO!
